<?php
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OwnerAuthController;
use App\Http\Controllers\CustomerAuthController;
use App\Http\Controllers\CustomerAccountController;
use Illuminate\Support\Facades\Route;
Route::get('/', HomeController::class)->name('home');
Route::get('/suche', [HomeController::class, 'search'])->name('search');
Route::get('/sitemap.xml', [HomeController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', fn () => response("User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ".route('sitemap')."\n", 200, ['Content-Type' => 'text/plain']));
Route::get('/produkte/honigsorten', [HomeController::class, 'honey'])->name('categories.honey');
Route::get('/produkte/honigmix', [HomeController::class, 'honeyMix'])->name('categories.honey-mix');
Route::get('/produkte/bienenprodukte', [HomeController::class, 'beeProducts'])->name('categories.bee-products');
Route::get('/produkte/cremes-salben', [HomeController::class, 'creamsAndSalves'])->name('categories.creams-salves');
Route::get('/produkte/kerzen', [HomeController::class, 'candles'])->name('categories.candles');
Route::get('/produkte/nahrungsergaenzungsmittel', [HomeController::class, 'supplements'])->name('categories.supplements');
Route::get('/produkte/seife', [HomeController::class, 'soaps'])->name('categories.soaps');
Route::get('/produkte/sirup', [HomeController::class, 'syrups'])->name('categories.syrups');
Route::get('/produkte/verschiedenes', [HomeController::class, 'miscellaneous'])->name('categories.miscellaneous');
Route::get('/produkte/halbedelsteine-co', [HomeController::class, 'gemstones'])->name('categories.gemstones');
Route::get('/produkte/{category}/{product}', [HomeController::class, 'product'])->name('products.show');
Route::get('/warenkorb', [HomeController::class, 'cart'])->name('cart');
Route::get('/kasse', [HomeController::class, 'checkoutPage'])->name('checkout.page');
Route::get('/kontakt', [HomeController::class, 'contact'])->name('contact');
Route::get('/versand', [HomeController::class, 'shipping'])->name('shipping');
Route::get('/widerruf', [HomeController::class, 'returns'])->name('returns');
Route::get('/impressum', [HomeController::class, 'imprint'])->name('imprint');
Route::get('/datenschutz', [HomeController::class, 'privacy'])->name('privacy');
Route::get('/agb', [HomeController::class, 'terms'])->name('terms');
Route::get('/besitzer', fn () => redirect()->route('customer.login'))->name('owner.login');
Route::post('/besitzer/registrieren', [OwnerAuthController::class, 'register'])->middleware('throttle:5,1')->name('owner.register');
Route::post('/besitzer/anmelden', [OwnerAuthController::class, 'login'])->middleware('throttle:5,1')->name('owner.authenticate');
Route::post('/besitzer/abmelden', [OwnerAuthController::class, 'logout'])->name('owner.logout');
Route::middleware(['owner.auth', 'throttle:60,1'])->prefix('admin')->group(function () {
    Route::get('/bestellungen', [HomeController::class, 'adminOrders'])->name('admin.orders');
    Route::post('/bestellungen/{id}/status', [HomeController::class, 'updateOrderStatus'])->name('admin.orders.status');
    Route::get('/produkte', [HomeController::class, 'adminProducts'])->name('admin.products');
    Route::post('/produkte/{category}/{product}', [HomeController::class, 'updateProduct'])->name('admin.products.update');
});
Route::get('/mein-konto', [OwnerAuthController::class, 'account'])->middleware('owner.auth')->name('owner.account');
Route::get('/kunden/login', [CustomerAuthController::class, 'showLogin'])->name('customer.login');
Route::get('/kunden/registrieren', [CustomerAuthController::class, 'showRegister'])->name('customer.register');
Route::post('/kunden/registrieren', [CustomerAuthController::class, 'register'])->middleware('throttle:5,1')->name('customer.register.store');
Route::post('/kunden/login', [CustomerAuthController::class, 'login'])->middleware('throttle:5,1')->name('customer.login.store');
Route::get('/kunden/passwort-vergessen', [CustomerAuthController::class, 'showForgot'])->name('customer.password.request');
Route::post('/kunden/passwort-vergessen', [CustomerAuthController::class, 'forgot'])->middleware('throttle:3,1')->name('customer.password.email');
Route::get('/kunden/passwort-reset/{token}', [CustomerAuthController::class, 'showReset'])->name('customer.password.reset');
Route::post('/kunden/passwort-reset', [CustomerAuthController::class, 'reset'])->middleware('throttle:5,1')->name('customer.password.update');
Route::get('/kunden/verifizieren/{customer}', [CustomerAuthController::class, 'verify'])->middleware('signed')->name('customer.verify');
Route::middleware('customer.auth')->group(function () {
    Route::get('/kundenkonto', [CustomerAccountController::class, 'index'])->name('customer.account');
    Route::put('/kundenkonto/profil', [CustomerAccountController::class, 'updateProfile'])->name('customer.profile.update');
    Route::put('/kundenkonto/passwort', [CustomerAccountController::class, 'updatePassword'])->middleware('throttle:5,1')->name('customer.password.change');
    Route::delete('/kundenkonto', [CustomerAccountController::class, 'deleteAccount'])->middleware('throttle:3,1')->name('customer.account.delete');
    Route::post('/kunden/abmelden', [CustomerAuthController::class, 'logout'])->name('customer.logout');
    Route::post('/kunden/verifizierung-senden', [CustomerAuthController::class, 'resend'])->middleware('throttle:3,1')->name('customer.verify.resend');
    Route::post('/kunden/adressen', [CustomerAccountController::class, 'storeAddress'])->name('customer.address.store');
    Route::put('/kunden/adressen/{address}', [CustomerAccountController::class, 'updateAddress'])->name('customer.address.update');
    Route::delete('/kunden/adressen/{address}', [CustomerAccountController::class, 'deleteAddress'])->name('customer.address.delete');
});
Route::post('/newsletter', [HomeController::class, 'newsletter'])->middleware('throttle:5,1')->name('newsletter');
Route::post('/checkout', [HomeController::class, 'checkout'])->middleware('throttle:10,1')->name('checkout');
Route::get('/danke', [HomeController::class, 'thankYou'])->name('checkout.thank-you');
Route::get('/vorschau/email-bestaetigung', function () {
    abort_unless(app()->isLocal(), 404);
    return view('emails.customer-verify', ['name' => 'Max Mustermann', 'url' => '#bestaetigen']);
});
Route::get('/vorschau/willkommens-email', function () {
    abort_unless(app()->isLocal(), 404);
    return view('emails.customer-welcome', ['customer' => (object) ['name' => 'Max Mustermann']]);
});
