<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Naturmarkt | Mein Konto</title><link rel="stylesheet" href="{{ asset('assets/css/site.css') }}"></head><body class="customer-account-body">
<header class="site-header"><nav class="nav container"><a class="brand" href="{{ route('home') }}"><img class="brand-logo" src="{{ asset('assets/images/naturmarkt-logo.svg') }}" alt="Naturmarkt"></a><div class="account-header-actions"><a class="button ghost" href="{{ route('home') }}">Zum Shop</a><form method="post" action="{{ route('customer.logout') }}">@csrf<button class="button ghost">Abmelden</button></form></div></nav></header>
<main class="account-page container">
<section class="account-welcome"><div><span class="eyebrow">Mein Naturmarkt</span><h1>Hallo, {{ $customer->name }}!</h1><p>Hier verwaltest du dein Profil, deine Lieferadressen und alle Bestellungen.</p></div><div class="account-status"><span class="status-dot {{ $customer->email_verified_at?'verified':'' }}"></span>{{ $customer->email_verified_at?'E-Mail bestätigt':'Bestätigung ausstehend' }}</div></section>
@if(session('success'))<p class="admin-success account-message">{{ session('success') }}</p>@endif
@if($errors->any())<p class="auth-error account-message">{{ $errors->first() }}</p>@endif
@if(!$customer->email_verified_at)<section class="account-alert"><div><strong>Bitte bestätige deine E-Mail-Adresse.</strong><p>So schützen wir dein Konto und können wichtige Bestellinformationen zustellen.</p></div><form method="post" action="{{ route('customer.verify.resend') }}">@csrf<button class="button primary">Bestätigung erneut senden</button></form></section>@endif

<nav class="account-tabs" aria-label="Kontobereiche"><a href="#uebersicht">Übersicht</a><a href="#bestellungen">Bestellungen</a><a href="#wunschliste">Wunschliste</a><a href="#adressen">Adressen</a><a href="#profil">Persönliche Daten</a><a href="#sicherheit">Sicherheit</a></nav>
<section class="account-panel" id="wunschliste"><div class="account-section-heading"><div><span class="eyebrow">Favoriten</span><h2>Meine Wunschliste</h2></div></div><div class="wishlist-grid">@forelse($wishlist as $wish)<article><strong>{{ str_replace('-',' ',ucfirst($wish->product_handle)) }}</strong><small>{{ str_replace('-',' ',ucfirst($wish->category_key)) }}</small><a href="{{ route('products.show',[$wish->category_key,$wish->product_handle]) }}">Produkt ansehen →</a><form method="post" action="{{ route('customer.wishlist.notify',$wish->id) }}">@csrf @method('PUT')<label class="inline-check"><input type="checkbox" name="notify" value="1" @checked($wish->notify_back_in_stock) onchange="this.form.submit()"> Bei Verfügbarkeit erinnern</label></form><form method="post" action="{{ route('customer.wishlist.toggle',[$wish->category_key,$wish->product_handle]) }}">@csrf<button class="text-danger">Entfernen</button></form></article>@empty<p>Deine Wunschliste ist noch leer.</p>@endforelse</div></section>

<section id="uebersicht" class="account-summary-grid"><article><span>Bestellungen</span><strong>{{ $orders->count() }}</strong><small>in deinem Kundenkonto</small></article><article><span>Adressen</span><strong>{{ $addresses->count() }}</strong><small>gespeicherte Lieferadressen</small></article><article><span>Kontostatus</span><strong>{{ $customer->email_verified_at?'Aktiv':'Offen' }}</strong><small>seit {{ date('d.m.Y',strtotime($customer->created_at)) }}</small></article></section>

<div class="account-content-grid"><div class="account-main-column">
<section class="account-panel" id="bestellungen"><div class="account-section-heading"><div><span class="eyebrow">Einkäufe</span><h2>Meine Bestellungen</h2></div><a href="{{ route('home') }}#kategorien">Weiter einkaufen</a></div>
@forelse($orders as $order)<details class="order-card"><summary><div><strong>Bestellung #{{ $order->id }}</strong><span>{{ date('d.m.Y · H:i',strtotime($order->created_at)) }} Uhr</span></div><div><span class="order-status">{{ $order->status }}</span><strong>{{ number_format($order->total,2,',','.') }} €</strong><span class="detail-arrow">⌄</span></div></summary><div class="order-details"><div class="order-items">@foreach($order->items as $item)<div><span>{{ $item['quantity'] ?? 1 }}× {{ $item['name'] ?? 'Produkt' }}</span><strong>{{ isset($item['price'])?number_format((float)$item['price']*(int)($item['quantity']??1),2,',','.').' €':'' }}</strong></div>@endforeach</div><dl><div><dt>Zahlungsart</dt><dd>{{ $order->payment_method }}</dd></div><div><dt>Zahlungsstatus</dt><dd>{{ $order->payment_status }}</dd></div><div><dt>Lieferadresse</dt><dd>{{ $order->address }}</dd></div>@if($order->shipping)<div><dt>Versand</dt><dd>{{ number_format($order->shipping,2,',','.') }} €</dd></div>@endif @if($order->tracking_number)<div><dt>Sendung</dt><dd>{{ $order->shipping_carrier }} · {{ $order->tracking_number }}</dd></div>@endif</dl><button type="button" class="button ghost" data-reorder="{{ base64_encode(json_encode($order->items)) }}">Erneut bestellen</button></div></details>@empty<div class="account-empty"><span>🛍️</span><h3>Noch keine Bestellungen</h3><p>Entdecke unsere ausgewählten Naturprodukte.</p><a class="button primary" href="{{ route('home') }}#kategorien">Sortiment ansehen</a></div>@endforelse</section>

<section class="account-panel" id="adressen"><div class="account-section-heading"><div><span class="eyebrow">Lieferung</span><h2>Gespeicherte Adressen</h2></div></div><div class="address-grid">@foreach($addresses as $address)<details class="address-card"><summary><div><strong>{{ $address->label }}</strong>@if($address->is_default)<span class="default-badge">Standard</span>@endif<p>{{ $address->name }}<br>{{ $address->street }}<br>{{ $address->postal_code }} {{ $address->city }} · {{ $address->country_code }}</p></div><span>Bearbeiten</span></summary><form method="post" action="{{ route('customer.address.update',$address->id) }}" class="account-form compact">@csrf @method('PUT')<input name="label" value="{{ $address->label }}" required><input name="name" value="{{ $address->name }}" required><input name="phone" value="{{ $address->phone }}" placeholder="Telefon"><input name="street" value="{{ $address->street }}" required><div class="form-row"><input name="postal_code" value="{{ $address->postal_code }}" required><input name="city" value="{{ $address->city }}" required></div><select name="country_code">@foreach($countries as $code=>$country)<option value="{{ $code }}" @selected($code===$address->country_code)>{{ $country['name'] }}</option>@endforeach</select><label class="inline-check"><input type="checkbox" name="is_default" value="1" @checked($address->is_default)> Standardadresse</label><button class="button primary">Änderungen speichern</button></form><form method="post" action="{{ route('customer.address.delete',$address->id) }}" onsubmit="return confirm('Adresse wirklich entfernen?')">@csrf @method('DELETE')<button class="text-danger">Adresse entfernen</button></form></details>@endforeach</div>
<details class="new-address-card" @if(!$addresses->count()) open @endif><summary>+ Neue Adresse hinzufügen</summary><form method="post" action="{{ route('customer.address.store') }}" class="account-form">@csrf<div class="form-row"><label>Bezeichnung<input name="label" placeholder="z. B. Zuhause" required></label><label>Name<input name="name" value="{{ $customer->name }}" required></label></div><label>Telefon<input name="phone" placeholder="Optional"></label><label>Straße und Hausnummer<input name="street" required></label><div class="form-row"><label>PLZ<input name="postal_code" required></label><label>Ort<input name="city" required></label></div><label>Land<select name="country_code">@foreach($countries as $code=>$country)<option value="{{ $code }}">{{ $country['name'] }}</option>@endforeach</select></label><label class="inline-check"><input type="checkbox" name="is_default" value="1"> Als Standardadresse verwenden</label><button class="button primary">Adresse speichern</button></form></details></section>
</div><aside class="account-side-column">
<section class="account-panel" id="profil"><span class="eyebrow">Profil</span><h2>Persönliche Daten</h2><form method="post" action="{{ route('customer.profile.update') }}" class="account-form">@csrf @method('PUT')<label>Name<input name="name" value="{{ old('name',$customer->name) }}" required></label><label>E-Mail-Adresse<input type="email" name="email" value="{{ old('email',$customer->email) }}" required></label><small>Nach einer E-Mail-Änderung ist eine erneute Bestätigung nötig.</small><button class="button primary">Daten speichern</button></form></section>
<section class="account-panel" id="sicherheit"><span class="eyebrow">Sicherheit</span><h2>Passwort ändern</h2><form method="post" action="{{ route('customer.password.change') }}" class="account-form">@csrf @method('PUT')<label>Aktuelles Passwort<input type="password" name="current_password" required autocomplete="current-password"></label><label>Neues Passwort<input type="password" name="password" minlength="12" required autocomplete="new-password"></label><label>Neues Passwort wiederholen<input type="password" name="password_confirmation" minlength="12" required autocomplete="new-password"></label><small>Mindestens 12 Zeichen, Groß- und Kleinbuchstaben sowie eine Zahl.</small><button class="button primary">Passwort ändern</button></form></section>
<section class="account-panel account-help"><span class="eyebrow">Hilfe</span><h2>Wir sind für dich da</h2><p>Fragen zu einer Bestellung oder einem Produkt?</p><a href="{{ route('contact') }}">Kontakt aufnehmen →</a><a href="{{ route('shipping') }}">Versandinformationen →</a><a href="{{ route('returns') }}">Widerruf & Rückgabe →</a></section>
<details class="account-danger"><summary>Konto und Datenschutz</summary><div><p>Du kannst dein Kundenkonto dauerhaft löschen. Aufbewahrungspflichtige Bestelldaten bleiben aus rechtlichen Gründen erhalten, werden aber vom Konto getrennt.</p><form method="post" action="{{ route('customer.account.delete') }}" class="account-form" onsubmit="return confirm('Kundenkonto wirklich dauerhaft löschen?')">@csrf @method('DELETE')<label>Passwort<input type="password" name="password" required></label><label>Zur Bestätigung „KONTO LÖSCHEN“ eingeben<input name="confirmation" required></label>@error('delete_account')<small class="auth-error">{{ $message }}</small>@enderror<button class="button danger">Konto dauerhaft löschen</button></form></div></details>
</aside></div></main><script src="{{ asset('assets/js/site.js') }}" defer></script></body></html>
