<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;background:#f2efe6;color:#26362a;font-family:Arial,sans-serif;padding:28px 12px">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border-radius:22px;overflow:hidden;box-shadow:0 12px 35px rgba(43,73,47,.12)">
<tr><td style="height:8px;background:#6c8c4a"></td></tr>
<tr><td align="center" style="padding:34px 32px 22px;background:#f8f6ee"><img src="{{ asset('assets/images/naturmarkt-logo.svg') }}" width="190" alt="Naturmarkt" style="max-width:190px;height:auto"><p style="margin:14px 0 0;color:#6b755f;font-size:13px;letter-spacing:1.4px;text-transform:uppercase">Natürlich · persönlich · mit Sorgfalt</p></td></tr>
<tr><td style="padding:38px 42px"><div style="display:inline-block;padding:7px 12px;border-radius:999px;background:#e9f0df;color:#466137;font-size:12px;font-weight:700;letter-spacing:.8px;text-transform:uppercase">Konto aktivieren</div><h1 style="margin:18px 0 14px;font-family:Georgia,serif;font-size:32px;line-height:1.2;color:#294932">Hallo {{ $name }}!</h1><p style="margin:0 0 24px;color:#596459;font-size:17px;line-height:1.65">Schön, dass du bei Naturmarkt dabei bist. Bestätige jetzt deine E-Mail-Adresse, damit dein Kundenkonto sicher aktiviert wird.</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="border-radius:12px;background:#315d38"><a href="{{ $url }}" style="display:inline-block;padding:15px 24px;color:#fff;text-decoration:none;font-size:16px;font-weight:700">E-Mail-Adresse bestätigen →</a></td></tr></table><p style="margin:24px 0 0;color:#7a8378;font-size:13px;line-height:1.5">Dieser Sicherheitslink ist 60 Minuten gültig. Falls du kein Konto erstellt hast, kannst du diese Nachricht ignorieren.</p></td></tr>
<tr><td align="center" style="padding:24px;background:#294932;color:#dce7d7;font-size:12px;line-height:1.6">Naturmarkt – ausgewählte Naturprodukte mit Herz<br><a href="{{ route('privacy') }}" style="color:#fff">Datenschutz</a> · <a href="{{ route('imprint') }}" style="color:#fff">Impressum</a></td></tr>
</table></td></tr></table></body></html>
