<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Http\RedirectResponse;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Log;use Illuminate\Support\Facades\Mail;use Illuminate\Support\Str;use Illuminate\View\View;use Symfony\Component\HttpFoundation\StreamedResponse;
class AdminManagementController extends Controller {
 private function log(Request $r,string $action,string $details=''):void{DB::table('admin_activity_logs')->insert(['owner_user_id'=>$r->session()->get('owner_user_id'),'action'=>$action,'details'=>$details,'ip_address'=>$r->ip(),'created_at'=>now(),'updated_at'=>now()]);}
 public function dashboard():View{
  $orders=DB::table('checkout_requests');
  $stats=['orders'=>(clone $orders)->count(),'revenue'=>(float)(clone $orders)->whereNotIn('status',['Storniert'])->sum('total'),'open'=>(clone $orders)->whereIn('status',['Neu','In Bearbeitung'])->count(),'customers'=>DB::table('customers')->count(),'low_stock'=>DB::table('product_overrides')->whereNotNull('stock')->where('stock','<=',5)->count()];
  $monthly=DB::table('checkout_requests')->selectRaw("DATE_FORMAT(created_at, '%Y-%m') month, SUM(total) revenue, COUNT(*) orders")->whereNotIn('status',['Storniert'])->where('created_at','>=',now()->subMonths(11)->startOfMonth())->groupBy('month')->orderBy('month')->get();
  return view('admin-dashboard',['stats'=>$stats,'monthly'=>$monthly,'recent'=>DB::table('checkout_requests')->latest()->limit(8)->get(),'lowStock'=>DB::table('product_overrides')->whereNotNull('stock')->where('stock','<=',5)->orderBy('stock')->limit(12)->get()]);
 }
 public function customers(Request $r):View{$q=trim((string)$r->query('q'));$customers=DB::table('customers')->when($q,fn($x)=>$x->where(fn($y)=>$y->where('name','like',"%$q%")->orWhere('email','like',"%$q%")))->orderByDesc('created_at')->get()->map(function($c){$c->orders=DB::table('checkout_requests')->where('customer_id',$c->id)->orWhere('email',$c->email)->latest()->get();return $c;});return view('admin-management',['section'=>'customers','customers'=>$customers,'q'=>$q]);}
 public function toggleCustomer(Request $r,int $id):RedirectResponse{$c=DB::table('customers')->find($id);abort_unless($c,404);DB::table('customers')->where('id',$id)->update(['is_blocked'=>!$c->is_blocked,'updated_at'=>now()]);$this->log($r,'customer.toggle',"Kunde #$id");return back()->with('success','Kundenstatus aktualisiert.');}
 public function orders(Request $r):View{$q=trim((string)$r->query('q'));$status=$r->query('status');$orders=DB::table('checkout_requests')->when($q,fn($x)=>$x->where(fn($y)=>$y->where('customer_name','like',"%$q%")->orWhere('email','like',"%$q%")->orWhere('id',$q)))->when($status,fn($x)=>$x->where('status',$status))->latest()->get();return view('admin-management',['section'=>'orders','orders'=>$orders,'q'=>$q,'status'=>$status]);}
 public function updateOrder(Request $r,int $id):RedirectResponse{$d=$r->validate(['status'=>['required','in:Neu,In Bearbeitung,Versendet,Erledigt,Storniert'],'payment_status'=>['required','in:Offen,Bezahlt,Erstattet'],'tracking_number'=>['nullable','string','max:120'],'shipping_carrier'=>['nullable','string','max:80']]);$order=DB::table('checkout_requests')->find($id);abort_unless($order,404);$d['shipped_at']=$d['status']==='Versendet'?($order->shipped_at?:now()):null;$d['updated_at']=now();DB::table('checkout_requests')->where('id',$id)->update($d);if($d['status']==='Versendet'&&$order->status!=='Versendet'){try{$tracking=$d['tracking_number']?"\nSendungsnummer: {$d['tracking_number']}\nVersanddienst: {$d['shipping_carrier']}":'';Mail::raw("Deine Naturmarkt-Bestellung #{$id} wurde versendet.{$tracking}",fn($m)=>$m->to($order->email)->subject("Bestellung #{$id} wurde versendet"));}catch(\Throwable $e){Log::warning('Versandmail fehlgeschlagen',['order_id'=>$id,'error'=>$e->getMessage()]);}}$this->log($r,'order.update',"Bestellung #$id");return back()->with('success','Bestellung aktualisiert.');}
 public function exportOrders():StreamedResponse{return response()->streamDownload(function(){$out=fopen('php://output','w');fputcsv($out,['ID','Datum','Kunde','E-Mail','Status','Zahlung','Gesamt','Tracking'],';');DB::table('checkout_requests')->orderBy('id')->each(fn($o)=>fputcsv($out,[$o->id,$o->created_at,$o->customer_name,$o->email,$o->status,$o->payment_status,$o->total,$o->tracking_number],';'));fclose($out);},'naturmarkt-bestellungen.csv',['Content-Type'=>'text/csv']);}
 public function invoice(int $id):View{$order=DB::table('checkout_requests')->find($id);abort_unless($order,404);$order->items=json_decode($order->cart?:'[]',true)?:[];return view('admin-invoice',compact('order'));}
 public function coupons():View{return view('admin-management',['section'=>'coupons','coupons'=>DB::table('coupons')->latest()->get()]);}
 public function storeCoupon(Request $r):RedirectResponse{$d=$r->validate(['code'=>['required','string','max:40','unique:coupons,code'],'type'=>['required','in:percent,fixed'],'value'=>['required','numeric','min:0.01'],'minimum_order'=>['required','numeric','min:0'],'expires_at'=>['nullable','date'],'max_uses'=>['nullable','integer','min:1']]);DB::table('coupons')->insert([...$d,'code'=>Str::upper($d['code']),'active'=>true,'created_at'=>now(),'updated_at'=>now()]);$this->log($r,'coupon.create',$d['code']);return back()->with('success','Gutschein erstellt.');}
 public function toggleCoupon(Request $r,int $id):RedirectResponse{$c=DB::table('coupons')->find($id);abort_unless($c,404);DB::table('coupons')->where('id',$id)->update(['active'=>!$c->active,'updated_at'=>now()]);return back()->with('success','Gutscheinstatus geändert.');}
 public function reviews():View{return view('admin-management',['section'=>'reviews','reviews'=>DB::table('product_reviews')->join('customers','customers.id','=','product_reviews.customer_id')->select('product_reviews.*','customers.name','customers.email')->latest('product_reviews.created_at')->get()]);}
 public function reviewStatus(Request $r,int $id):RedirectResponse{$d=$r->validate(['status'=>['required','in:approved,rejected']]);DB::table('product_reviews')->where('id',$id)->update(['status'=>$d['status'],'updated_at'=>now()]);$this->log($r,'review.'.$d['status'],"Bewertung #$id");return back()->with('success','Bewertung aktualisiert.');}
 public function activity():View{return view('admin-management',['section'=>'activity','logs'=>DB::table('admin_activity_logs')->latest()->limit(200)->get()]);}
}
